arrowParens: always
printWidth: 100
trailingComma: 'all'
tabWidth: 2
semi: true
singleQuote: true

# Maintain the style of original webviz-core js files until they are ported to typescript
overrides:
  - files: 'app/**/*.js'
    options:
      printWidth: 120
      arrowParens: always
      jsxBracketSameLine: true
      trailingComma: es5
      singleQuote: false
