name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Configure Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: .yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn install --immutable
    - run: yarn run webpack --mode production
      env:
        # Our build is so large that it requires more memory from v8
        NODE_OPTIONS: --max-old-space-size=4096
