name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Configure Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --immutable
      - run: yarn run lint:nofix
      - run: yarn run build:prod
