name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    # Run each command in parallel with the same setup steps.
    strategy:
      fail-fast: false
      matrix:
        config:
          # Specify names so that the GitHub branch protection settings for
          # required checks don't need to change if we ever change the commands used.
          - name: lint
            command: lint:nofix
          - name: build
            command: build:prod
          - name: test
            command: test --maxWorkers=100%

    name: ${{ matrix.config.name }}

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Configure Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.x
      - name: Restore cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            .yarn/cache
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --immutable
      - run: yarn run ${{ matrix.config.command }}
